books/urls.py
from django.urls import path
from . import views

app_name= 'books'

urlpatterns = [
    path('', views.HomePage, name='index'),
    path('books', views.index, name='HomePage'),
    path('Search', views.Search, name='Search'),
    path('DisplayBook', views.DisplayBook, name='DisplayBook'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name= 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('Licence/', views.Licence, name='Licence'),

]

books/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=500)
    Summary = models.TextField(max_length=700)
    created_on = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=500)
    cover = models.ImageField(upload_to='images/', default=None)
    upload = models.FileField(upload_to ='uploads/', blank=True)

users/models.py
from django.db import models

# Create your models here.

books/forms.py
from django import forms
from .models import Book

class BookSearch(forms.Form):
    BookName = forms.CharField(max_length=10000)




#class BookSearch(forms.ModelForm):
#    class Meta:
#        model = Book
#        fields = ['text']
#        labels = {'text': ''}

books/views.py
from django.shortcuts import render, HttpResponse
from . import forms
from .models import Book
from django.contrib.auth.decorators import login_required



def HomePage(request):
    return render(request, 'library/home.html')



@login_required
def index(request):
    books = Book.objects.all()
    context = {'books': books}

    return render(request, 'library/index.html', context)



@login_required
def DisplayBook(request):
    if request.method == 'POST':
        data = request.POST.get('BookPath')
        with open(data, 'rb') as pdf:
            response = HttpResponse(pdf.read() ,content_type='application/pdf')
            response['Content-Disposition'] = f'inline;filename={data}'
            return response
    else:
        return HttpResponse('Error 404')


@login_required
def Search(request):
    print('excutec')
    query = request.GET.get('q')
    print(query)
    context = Book.objects.filter(title__icontains=query)
    context = {'books': context}
    return render(request, 'library/index.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form= UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            login(request, new_user)
            return redirect('books:index')
        
    context = {'form': form}
    return render(request, 'registration/register.html', context)

def Licence(request):

    return render(request, 'registration/licence.html')

books/templates/library/DisplayBook.html
{% extends "library/base.html" %}

{% block content %}

<style>
.make_light_text
{
    color:black;
}

.pdf-container {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}

iframe {
  max-width: 100%;
  max-height: 100%;
}

</style>




<div class="pdf-container">

    <iframe src="{url 'book:DisplayBook' }" width="100%" height="100%" frameborder="0" type="application/pdf"></iframe>

</div>
        

{% endblock %}

books/templates/library/base.html
<!doctype html>


<html lang="en">
   <head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
      <title>
        {% block title %}

        {% endblock %}
      </title>
   </head>
   <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">MyLibrary</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'books:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'books:HomePage' %}">Books</a>
            </li>
        </ul>

        <ul class="navbar-nav">
        {% if user.is_authenticated %}
		      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             Hello, {{ user.username }}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item make_red" href="{% url 'users:logout' %}">Log Out</a></li>
          </ul>
                    
          </li>
        {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %} ">Register</a>
              </li>
          
        {% endif %}
      </ul>
      </div>
    </nav>
      {% block content %}

      {% endblock %}
      <!-- Future Content here -->



      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src='https://kit.fontawesome.com/a076d05399.js'></script>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script></head>
   </body>
   <style>

      .make_red{
        color: red;
      }
      body{
        background-color: #212121;
        color: white;
      }
      .make_text_white{
        color: white;
      }
   </style>
</html>

books/templates/library/home.html
{% extends 'library/base.html' %}


{% block title %}
    Home Page
{% endblock %}


{%block content%}
<style>

@import url(https://fonts.googleapis.com/css?family=Nunito);

html {
  height: 100%;
  overflow: hidden;
}

body { 
  margin:0;
  padding:0;
	perspective: 1px;
	transform-style: preserve-3d;
  height: 100%;
  overflow-y: scroll;
  overflow-x: hidden;
  font-family: Nunito;
}

h1 {
   font-size: 250%
}

p {
  font-size: 140%;
  line-height: 150%;
  color: #333;
}

.slide {
  position: relative;
  padding: 25vh 10%;
  min-height: 100vh;
  width: 100vw;
  box-sizing: border-box;
  box-shadow: 0 -1px 10px rgba(0, 0, 0, .7);
	transform-style: inherit;
}

img {
  position: absolute;
  top: 50%;
  left: 35%;
  width: 320px;
  height: 240px;
  transform: translateZ(.25px) scale(.75) translateX(-94%) translateY(-100%) rotate(2deg);
  padding: 10px;
  border-radius: 5px;
  background: rgba(240,230,220, .7);
  box-shadow: 0 0 8px rgba(0, 0, 0, .7);
}

img:last-of-type {
  transform: translateZ(.4px) scale(.6) translateX(-104%) translateY(-40%) rotate(-5deg);
}

.slide:before {
  content: "";
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  box-shadow: 0 0 8px 1px rgba(0, 0, 0, .7);
}

.title {
  width: 50%;
  padding: 5%;
  border-radius: 5px;
  background: rgba(240,230,220, .7);
  box-shadow: 0 0 8px rgba(0, 0, 0, .7);
}

.slide:nth-child(2n) .title {
  margin-left: 0;
  margin-right: auto;
}

.slide:nth-child(2n+1) .title {
  margin-left: auto;
  margin-right: 0;
}

.slide, .slide:before {
  background: 50% 50% / cover;  
}

.header {
  text-align: center;
  font-size: 175%;
  color: #fff;
  text-shadow: 0 2px 2px #000;
}

#title {
  background-image: url("https://lorempixel.com/640/480/abstract/6/");
  z-index:2;
}

#title h1 {
 transform: translateZ(.25px) scale(.75);
 transform-origin: 50% 100%;

}

#slide1:before {
  background-image: url("https://lorempixel.com/640/480/abstract/4/");
  transform: translateZ(-1px) scale(2);
}

#slide2 {
  background-image: url("https://lorempixel.com/640/480/abstract/3/");
  z-index:2;
}

#slide3:before {
  background-image: url("https://lorempixel.com/640/480/abstract/5/");
  transform: translateZ(-1px) scale(2);
}

#slide4 {
  background: #222;
}


</style>


<div id="title" class="slide header">
    <h1>Welcome to eLibrary!</h1>
  </div>
  
  <div id="slide1" class="slide">
    <div class="title">
      <h1>Free ebooks!</h1>
      <p>MyLibrary is a modern library with 1000+ ebooks. They are all free and there are up 5000+ ebooks for premuim users</p>
    </div>
  </div>
  
  <div id="slide2" class="slide">
    <div class="title">
      <h1>Very Safe!</h1>
      <p>Our system is very safe and we our database is very hard to be hacked. We do not spam email, so that you can trust us giving us your email.</p>
    </div>
  </div>
  
  <div id="slide3" class="slide">
    <div class="title">
      <h1>Contains All subjects</h1>
      <p>There are many books which you can download and read!</p>
    </div>
  </div>

  <div id="slide4" class="slide header">
      <h1>Sign Up now for free... No credit card required!</h1>
</div>

{%endblock%}

books/templates/library/index.html
{% extends "library/base.html" %}

{% block content %}



<style>
.make_light_text
{
    color:black;
}
</style>
<br/>

<form class="d-flex" action="{% url 'books:Search' %}" method="get">
    <input type="text" name="q" placeholder="Search" class="form-control me-2">
    <button type="submit" class="btn btn-outline-success">Search</button>
  </form>
<br/>

<h1>{{ book.upload }}</h1>
{% for book in books %}
    <div class="card mb-3" style="max-width: 600px;">
        <div class="row g-0">
        <div class="col-md-4">
            <img id="image" src="{{book.cover.url}}" class="img-fluid rounded-start">
        </div>
        <div class="col-md-8">
            <div class="card-body">
            <h5 class="card-title make_light_text">{{ book.title }}</h5>
            <p class="card-text make_light_text">{{ book.Summary }}</p>
            <p class="card-text"><small class="text-muted">Author: {{ book.author }}</small></p>
            <div class="btn-group">
            <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                Options
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" download href="media/{{ book.upload }}">Download PDF version</a></li>
          
                  <form method="POST" action="{% url 'books:DisplayBook' %}">
                    {% csrf_token %}
                    <input type="hidden" name="BookPath" value="media/{{ book.upload }}">
                    <li><button class="dropdown-item" type="submit">Read This Book In Browser</button></li>
                  </form>              
                </ul>
              </div>
            </div>
        </div>
        </div>
    </div>








    {% empty %}
    
        <h1>No Results Found :(</h1>
        <a href= "{% url 'books:HomePage' %}"><button type="button" class="btn btn-danger">Go Back To All Books</button></a>
        
{% endfor %}


{% endblock %}